(library (text-utils describe)
  (export describe)
  (import (scheme))
  (define (describe x)
    (if (and (integer? x) (exact? x))
        (if (< x (expt 10 9))
            (format "~r" x)
            "billions and billions of")
        "other")))
